/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_jni_STSystemFunction */

#ifndef _com_common_android_permission_PermissionJNI_H
#define _com_common_android_permission_PermissionJNI_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_jni_STSystemFunction
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_permission_PermissionJNI_nativeInit
  (JNIEnv *, jobject);
    
//    add by tangjl
JNIEXPORT void JNICALL Java_com_common_android_permission_PermissionJNI_nativeNotifyGranted
   (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
